version: "3.7"

volumes:
  ticket-data:

services:
  postgres:
    container_name: ticket-db
    image: postgres:15.8-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: vst
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ticket-database
    volumes:
      - ticket-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

