spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/ticket-database
    username: vst
    password: admin
    driverClassName: org.postgresql.Driver

  flyway:
    enabled: true
    user: vst
    password: admin
    schemas: public
    url: jdbc:postgresql://localhost:5434/ticket-database